### ISSUE TITLE
API /blockchain is very slow

### ISSUE THREAD

**Issue by dlecan** [unik-name/uns-core#335]
Requesting `/api/blockchain` takes so much time!

It slows down the explorer, which requests it every 8s.

Would it be possible to speed it up?
Using cache?

# Actual result

```
time http https://api.uns.network/api/blockchain
...
real	0m4,424s
```

This time is constant, so there isn't any cache here.

# Expected

As fast as Ark's blockchain:

```
time http https://api.ark.io/api/blockchain
...
real	0m0,567s
```

**Comment by peterjah** [comment]
It is because of supply computation. It requires to parse all transactions leading to supply creation (voucher nft mints and alive demands)

**Comment by peterjah** [comment]
a solution would be to build supply value blocks by blocks, store it and update it for every new blocks!

**Comment by peterjah** [comment]
Another (and more simple) solution proposition here:
https://github.com/unik-name/unn-core/pull/339
